// 1 - IMPORTAR EL ARCHIVO ./src/data/movies.js
// 2 - CREA UN ARCHIVO functions.js Y EXPORTAR DEL MISMO LA FUNCIÓN getMoviesByYear
// 3 - LA FUNCIÓN getMoviesByYear DEBE RETORNAR UNA PROMESA QUE DURE 2 SEGUNDOS (usar setTimeout) Y RESUELVA (resolve) EL RESULTADO DE LA BÚSQUEDA.
// 4 - VALIDAR QUE EL ARGUMENTO DE LA FUNCIÓN SEA UN NUMERO Y QUE EL NUMERO SEA MAYOR A 1000 Y MENOR A 2024. ENVIAR EL ERROR POR EL "reject".
// 5 - SI NO EXISTEN PELÍCULAS QUE RESUELVA CON EL MENSAJE "No existen películas en ese año"
// 6 - MOSTRAR POR CONSOLA LA RESPUESTA DE LA PROMESA.